// Knito prototype — seed data + i18n strings
window.KNITO_DATA = (function(){

  // -------------------- i18n --------------------
  const i18n = {
    no: {
      appName: 'Knito',
      tagline: 'Strikkeprosjekter, samlet.',
      tabs: { projects: 'Prosjekter', yarn: 'Garn', needles: 'Pinner', stats: 'Statistikk' },
      nav: { back: 'Tilbake', edit: 'Rediger', save: 'Lagre', cancel: 'Avbryt', delete: 'Slett', more: 'Mer' },
      actions: {
        newProject: 'Nytt prosjekt',
        addYarn: 'Nytt garn',
        addNeedle: 'Ny pinne',
        openRecipe: 'Åpne oppskrift',
        startSession: 'Start økt',
        stopSession: 'Stopp økt',
        attachPhoto: 'Legg til bilde',
        attachRecipe: 'Last opp oppskrift',
        signIn: 'Logg inn',
        signUp: 'Opprett konto',
        getStarted: 'Kom i gang',
      },
      status: { Aktiv: 'Aktiv', 'På vent': 'På vent', Planlagt: 'Planlagt', Fullført: 'Fullført', Arkivert: 'Arkivert' },
      filter: { all: 'Alle', active: 'Aktive', paused: 'På vent', planned: 'Planlagt', done: 'Fullført' },
      sort: { recent: 'Nyeste', name: 'Navn', progress: 'Progresjon' },
      fields: {
        progress: 'Progresjon', started: 'Startet', finished: 'Ferdig',
        yarn: 'Garn', needles: 'Pinner', recipe: 'Oppskrift', notes: 'Notater',
        gauge: 'Strikkefasthet', pattern: 'Mønster', time: 'Tid brukt',
        counter: 'Teller', skeins: 'Nøster', inStock: 'På lager',
        usedIn: 'Brukes i', category: 'Kategori',
      },
      empty: {
        noProjects: 'Ingen prosjekter ennå',
        noProjectsHint: 'Begynn på ditt første strikkeprosjekt',
        noYarn: 'Garnlageret er tomt',
        noNeedles: 'Ingen pinner registrert',
        noAttachment: 'Ingen oppskrift lagt til',
      },
      session: { active: 'Aktiv økt', today: 'I dag', thisWeek: 'Denne uken', total: 'Totalt' },
      onboarding: [
        { title: 'Velkommen til Knito', body: 'Hold styr på prosjektene, garnet og pinnene dine – på ett sted.' },
        { title: 'Åpne oppskriften raskt', body: 'Fest PDF, bilde eller lenke til hvert prosjekt. Ett trykk for å åpne.' },
        { title: 'Garn og pinner snakker sammen', body: 'Prosjektene vet hva du har på lager – og omvendt.' },
      ],
      auth: {
        welcomeBack: 'Velkommen tilbake',
        signInSub: 'Logg inn for å åpne prosjektene dine',
        email: 'E-post', password: 'Passord',
        forgot: 'Glemt passord?',
        noAccount: 'Ingen konto?',
      },
      units: { minutes: 'min', hours: 't', rows: 'omg', stitches: 'm' },
      months: ['jan','feb','mar','apr','mai','jun','jul','aug','sep','okt','nov','des'],
    },
    en: {
      appName: 'Knito',
      tagline: 'Your knitting projects, together.',
      tabs: { projects: 'Projects', yarn: 'Yarn', needles: 'Needles', stats: 'Stats' },
      nav: { back: 'Back', edit: 'Edit', save: 'Save', cancel: 'Cancel', delete: 'Delete', more: 'More' },
      actions: {
        newProject: 'New project',
        addYarn: 'Add yarn',
        addNeedle: 'Add needle',
        openRecipe: 'Open pattern',
        startSession: 'Start session',
        stopSession: 'Stop session',
        attachPhoto: 'Add photo',
        attachRecipe: 'Attach pattern',
        signIn: 'Sign in',
        signUp: 'Create account',
        getStarted: 'Get started',
      },
      status: { Aktiv: 'Active', 'På vent': 'On hold', Planlagt: 'Planned', Fullført: 'Finished', Arkivert: 'Archived' },
      filter: { all: 'All', active: 'Active', paused: 'On hold', planned: 'Planned', done: 'Finished' },
      sort: { recent: 'Recent', name: 'Name', progress: 'Progress' },
      fields: {
        progress: 'Progress', started: 'Started', finished: 'Finished',
        yarn: 'Yarn', needles: 'Needles', recipe: 'Pattern', notes: 'Notes',
        gauge: 'Gauge', pattern: 'Pattern', time: 'Time spent',
        counter: 'Counter', skeins: 'Skeins', inStock: 'In stock',
        usedIn: 'Used in', category: 'Category',
      },
      empty: {
        noProjects: 'No projects yet',
        noProjectsHint: 'Start your first knitting project',
        noYarn: 'Your yarn stash is empty',
        noNeedles: 'No needles yet',
        noAttachment: 'No pattern attached',
      },
      session: { active: 'Active session', today: 'Today', thisWeek: 'This week', total: 'Total' },
      onboarding: [
        { title: 'Welcome to Knito', body: 'Keep your projects, yarn and needles in one calm place.' },
        { title: 'Open your pattern fast', body: 'Attach a PDF, image or link to any project. One tap to open.' },
        { title: 'Yarn & needles talk to projects', body: 'Projects know what’s in your stash — and the other way around.' },
      ],
      auth: {
        welcomeBack: 'Welcome back',
        signInSub: 'Sign in to open your projects',
        email: 'Email', password: 'Password',
        forgot: 'Forgot password?',
        noAccount: 'No account?',
      },
      units: { minutes: 'min', hours: 'h', rows: 'rows', stitches: 'st' },
      months: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    },
  };

  // -------------------- seed projects --------------------
  const projects = [
    {
      id: 'p1',
      name: 'Marius-genser',
      nameEn: 'Marius sweater',
      category: 'Genser', categoryEn: 'Sweater',
      progress: 62,
      status: 'Aktiv',
      startDate: '2026-02-04',
      endDate: null,
      recipeName: 'Marius-genser_voksen.pdf',
      recipeSize: '2.1 MB',
      recipePages: 8,
      hasAttachment: true,
      notes: 'Strikker i løs fasthet – gikk opp én pinnestørrelse.\nDesigndetaljer på skulder fra side 4.',
      notesEn: 'Knitting a bit loose — went up one needle size.\nShoulder detail on page 4.',
      image: 'wool-cream',
      accent: '#c9a58c',
      yarnIds: ['y1', 'y2'],
      needleIds: ['n1', 'n2'],
      timeMinutes: 2340,
      counter: { rows: 142, target: 228 },
      sessions: [45, 60, 90, 30, 75, 50, 110],
      gauge: '22 m × 30 omg / 10cm',
    },
    {
      id: 'p2',
      name: 'Sjal – Haruni',
      nameEn: 'Shawl – Haruni',
      category: 'Sjal', categoryEn: 'Shawl',
      progress: 28,
      status: 'Aktiv',
      startDate: '2026-03-21',
      endDate: null,
      recipeName: 'haruni-shawl.pdf',
      recipeSize: '850 KB',
      recipePages: 4,
      hasAttachment: true,
      notes: 'Kronediagram starter omg 41. Legg ut livline hver 10. omg.',
      notesEn: 'Crown chart begins row 41. Drop a lifeline every 10 rows.',
      image: 'wool-rose',
      accent: '#c9856b',
      yarnIds: ['y3'],
      needleIds: ['n3'],
      timeMinutes: 780,
      counter: { rows: 40, target: 142 },
      sessions: [30, 45, 60, 20, 0, 80, 40],
      gauge: '18 m × 26 omg / 10cm',
    },
    {
      id: 'p3',
      name: 'Ullsokker',
      nameEn: 'Wool socks',
      category: 'Sokker', categoryEn: 'Socks',
      progress: 85,
      status: 'Aktiv',
      startDate: '2026-03-30',
      endDate: null,
      recipeName: null,
      recipeSize: null,
      hasAttachment: false,
      notes: 'Andre sokken – hælkile påbegynt.',
      notesEn: 'Second sock — heel turn started.',
      image: 'wool-oat',
      accent: '#9a8773',
      yarnIds: ['y4'],
      needleIds: ['n4'],
      timeMinutes: 420,
      counter: { rows: 68, target: 80 },
      sessions: [25, 40, 35, 50, 40, 30, 20],
      gauge: null,
    },
    {
      id: 'p4',
      name: 'Babyteppe',
      nameEn: 'Baby blanket',
      category: 'Teppe', categoryEn: 'Blanket',
      progress: 0,
      status: 'Planlagt',
      startDate: null,
      endDate: null,
      recipeName: 'baby-blanket-ravelry.pdf',
      recipeSize: '1.4 MB',
      recipePages: 3,
      hasAttachment: true,
      notes: 'Gave til Ingrid i juni.',
      notesEn: 'Gift for Ingrid in June.',
      image: 'wool-cream',
      accent: '#d3b89a',
      yarnIds: [],
      needleIds: [],
      timeMinutes: 0,
      counter: null,
      sessions: [],
      gauge: null,
    },
    {
      id: 'p5',
      name: 'Setesdalskofte',
      nameEn: 'Setesdal cardigan',
      category: 'Kofte', categoryEn: 'Cardigan',
      progress: 100,
      status: 'Fullført',
      startDate: '2025-10-10',
      endDate: '2026-02-01',
      recipeName: 'setesdal_oppskrift.pdf',
      recipeSize: '3.2 MB',
      recipePages: 12,
      hasAttachment: true,
      notes: 'Ferdig! Blokka i badet, strøk aldri denne.',
      notesEn: 'Done! Blocked in the bath, never ironed.',
      image: 'wool-char',
      accent: '#4a443f',
      yarnIds: ['y5', 'y6'],
      needleIds: ['n1'],
      timeMinutes: 8640,
      counter: null,
      sessions: [],
      gauge: '24 m × 32 omg / 10cm',
    },
    {
      id: 'p6',
      name: 'Mohair-topp',
      nameEn: 'Mohair top',
      category: 'Topp', categoryEn: 'Top',
      progress: 45,
      status: 'På vent',
      startDate: '2026-01-15',
      endDate: null,
      recipeName: null,
      hasAttachment: false,
      notes: 'Venter på mer Tynn Silk Mohair – dyelot 2024.',
      notesEn: 'Waiting for more Tynn Silk Mohair — dyelot 2024.',
      image: 'wool-rose',
      accent: '#d9a9b0',
      yarnIds: ['y7'],
      needleIds: ['n2'],
      timeMinutes: 660,
      counter: { rows: 54, target: 120 },
      sessions: [],
      gauge: null,
    },
  ];

  // -------------------- yarn stash --------------------
  const yarn = [
    { id: 'y1', name: 'Sandnes Peer Gynt', color: 'Natur', colorHex: '#e8dcc8', weight: 'DK', skeins: 6, fiber: '100% Ull', yardage: '91m / 50g', dyeLot: 'A4-2211', usedInIds: ['p1'] },
    { id: 'y2', name: 'Sandnes Peer Gynt', color: 'Marineblå', colorHex: '#2d3a52', weight: 'DK', skeins: 3, fiber: '100% Ull', yardage: '91m / 50g', dyeLot: 'B1-2311', usedInIds: ['p1'] },
    { id: 'y3', name: 'Rauma Finullgarn', color: 'Gammelrosa', colorHex: '#c88a85', weight: 'Fingering', skeins: 4, fiber: '100% Ull', yardage: '175m / 50g', dyeLot: 'K7-2402', usedInIds: ['p2'] },
    { id: 'y4', name: 'Drops Fabel', color: 'Havregrå', colorHex: '#b9aa93', weight: 'Fingering', skeins: 2, fiber: '75% Ull, 25% Nylon', yardage: '205m / 50g', dyeLot: '903', usedInIds: ['p3'] },
    { id: 'y5', name: 'Rauma 3-tråds strikkegarn', color: 'Kull', colorHex: '#2a2622', weight: 'Sport', skeins: 0, fiber: '100% Ull', yardage: '120m / 50g', dyeLot: '—', usedInIds: ['p5'] },
    { id: 'y6', name: 'Rauma 3-tråds strikkegarn', color: 'Ubleket', colorHex: '#efe6d5', weight: 'Sport', skeins: 0, fiber: '100% Ull', yardage: '120m / 50g', dyeLot: '—', usedInIds: ['p5'] },
    { id: 'y7', name: 'Sandnes Tynn Silk Mohair', color: 'Dus rosa', colorHex: '#ddb8b9', weight: 'Lace', skeins: 1, fiber: '60% Mohair, 25% Silke, 15% Ull', yardage: '212m / 25g', dyeLot: '2024', usedInIds: ['p6'] },
    { id: 'y8', name: 'Hillesvåg Sølje Pelsullgarn', color: 'Lyng', colorHex: '#7d6480', weight: 'DK', skeins: 5, fiber: '100% Pelsull', yardage: '100m / 50g', dyeLot: 'P-24', usedInIds: [] },
  ];

  // -------------------- needle inventory --------------------
  const needles = [
    { id: 'n1', size: '3.5mm', type: 'Rundpinne', typeEn: 'Circular', length: '80cm', material: 'Bambus', materialEn: 'Bamboo', quantity: 2, usedInIds: ['p1', 'p5'] },
    { id: 'n2', size: '4mm', type: 'Rundpinne', typeEn: 'Circular', length: '60cm', material: 'Metall', materialEn: 'Metal', quantity: 1, usedInIds: ['p1', 'p6'] },
    { id: 'n3', size: '4.5mm', type: 'Rundpinne', typeEn: 'Circular', length: '100cm', material: 'Tre', materialEn: 'Wood', quantity: 1, usedInIds: ['p2'] },
    { id: 'n4', size: '2.5mm', type: 'Strømpepinne', typeEn: 'DPN', length: '20cm', material: 'Metall', materialEn: 'Metal', quantity: 5, usedInIds: ['p3'] },
    { id: 'n5', size: '3mm', type: 'Rundpinne', typeEn: 'Circular', length: '80cm', material: 'Bambus', materialEn: 'Bamboo', quantity: 1, usedInIds: [] },
    { id: 'n6', size: '5mm', type: 'Jumperpinne', typeEn: 'Straight', length: '35cm', material: 'Tre', materialEn: 'Wood', quantity: 2, usedInIds: [] },
    { id: 'n7', size: '6mm', type: 'Rundpinne', typeEn: 'Circular', length: '100cm', material: 'Metall', materialEn: 'Metal', quantity: 1, usedInIds: [] },
  ];

  return { i18n, projects, yarn, needles };
})();
